#pragma once

#define	MINIMAL_WIDTH_WINDOW 800
#define	MINIMAL_HEIGHT_WINDOW 600
#define RIGHT_PLACE 180

#define ID_LIST 502

#define MAIN_WINDOW_BUTTON_START 42
#define MAIN_WINDOW_LEAVE_GAME 43

#define MESSAGE_NEWNAME WM_USER+1
#define MESSAGE_UPDATELIST WM_USER+2


#define MESSAGE_STARTGAME_OUT WM_USER+20
#define MESSAGE_STARTGAME_IN WM_USER+21
#define MESSAGE_CONNECTION_FAILD WM_USER+22
#define MESSAGE_CONNECTION_SUCCESS WM_USER+23
#define MESSAGE_CONNECTION_CLOSE WM_USER+24

#define MESSAGE_CONNECTION_ADDPOINT WM_USER+30
#define MESSAGE_CONNECTION_END WM_USER+31
#define MESSAGE_CONNECTION_LEAVE WM_USER+32

#define CLEAN_AREA WM_USER+128

#define EDIT_ID 1
#define BUTTON_ED_ID 2
#define BUTTON_START_GAME 3

#define MaxNameSize 16